[editor]
line-number = "relative"
true-color = true
color-modes = true

[editor.statusline]
left = ["mode", "separator", "spinner", "file-name"]
right = ["diagnostics", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
separator = "" #   

[editor.indent-guides]
render = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[theme]
name = "github_dark"

[theme.overrides]
"ui.background" = {}
"ui.cursor" = { fg = "black", bg = "#E9E0C9" }
"ui.statusline" = { fg = "white", bg = "#000000" }
"ui.statusline.normal" = { fg = "black", bg = "white" }
"ui.statusline.insert" = { fg = "black", bg = "white" }
"ui.statusline.select" = { fg = "black", bg = "white" }
"ui.statusline.separator" = { fg = "white", bg = "#000000" }